### PR TITLE
scripts

### PR DESCRIPTION
**Pull request by osendott**
automated.sh is the full script, generate-no-edits.sh does the conversion/generation but I commented out the color-replace stuff for testing. give these a shot, refer to previous conversation regarding issues. It appears all arguments are getting passed to xcursorgen the way the should, but output files are blank. oh, you'll have to create an output folder in the same directory as the script and the /src directory.. I end up with error reading .png files I believe.

### CODE REVIEW

**Comment by uloco** [comment]
I tested it, found out that there is a `PNG error while reading foo.png!` every conversion.
This happens because in the `.cursor` files, the file name is written without a path. It is just some pathing issue ( you would need to change the working directory to `src/` and fire `xcursorgen` from there. I also realized, that the png and svg images and are not generated in `automated.sh`, perhaps because the `xcursorgen` throws an error for each file.

**Comment by osendott** [comment]
ok, I've got it fixed now. It does everything except recolor the svg's first (I've taken that part out for now until we figure out the best way to figure out how to get the color to be replaced) it'll then generate png files from the svg files and then generate the cursor files using xcursorgen. works smooth this time. I still need to go through and comment the code, but basically all that changed was running the xcursogen command in a subshell and changing the current directory to the /src directory as you suggested. I wouldn't have though it mattered the directory you were in if you were passing full paths to xcursorgen, but apparently it does? anyways, should be fine now.

Is there a way you could name the objects to be recolored something unique in the svg's so the script could search the svg files for that object name, get it's current color and the replace it? Or it might just be best to let the user use inkscape to color theme, and then just let the script do the conversion/generation?

**Comment by uloco** [comment]
Looks good! For the coloring purposes: I think we should accept a few color values in words like `red`, `blue`, `brown`, etc. (this could be the same colors as in [numix-folders](https://github.com/numixproject/numix-folders) primary ones) and `default`(for the cursor defaults, which should be stored somewhere, perhaps hardcoded so they don't change) and `custom` to ask after the hex codes (for individual styling). This is only concerning the colored parts of the cursor. Additionally we could make it possible to choose from a 'light' and a 'dark' color scheme, which would mean just switching the light gray and black outline part of the cursor.
If we want to make the whole colors customizeable (like outline/fill color, plus, minus, arrow, etc.), a config file would be better I think. This could be an additional option for the customizing freaks out there. (could be a feature in the future, not so important right now I think...)

What do you think?

**Comment by uloco** [comment]
Shouldn't we move these changes to a branch, so the master branch stays without development states? I created a new branch `color-customization`. Please make another pull request to this branch.

**Comment by osendott** [comment]
yeah i'm thinking for now, just let the script do what it needs to do for the cursors we have, generate the pngs (just in case someone wants to edit manually) and then generate the actualy cursors themselves. and then we can go ahead and start working on the script to handle all the colorization manually would be what I think. As it stands right now, your original goal (I believe) has been accomplished? this is v1 if you will, and step it up from there, a light/dark option, then from there a few hard-coded options, and then on from there. That way we can make sure each previous purpose is working, and don't bite off more than we can chew, which is kinda what happened here, instead of testing each piece by iteslf, it took the 2 scripts I had, pasted them into a file, added the xcursorgen part and hoped they played well together, which they didn't.. would've been ahead to just start from scratch. so yeah, i'll submit a new request to the new branch, then tomorrow (now it's getting late on this side of the world haha) i'll start work on a light/dark option. it'll help if you could, when you get time, get some new svg's together, or just edit the old ones, but try and label each part and keep that in a file so I'll know what to point the script towards when customizing. IE outline, main bg, color, etc. that way if we want to change the outline of all cursors, I can just have the script loop through all the files and find the "outline" objects, and change it's color.

also, if it'd be easier than talking back and forth here, my e-mail is william.osendott@gmail.com

**Pull request closed without merging**
