### PR TITLE
automation scripts

### PR DESCRIPTION
**Pull request by osendott**
created a clean-fork of the repo so I could start from scratch. 
Here are two scripts, one I use to replace hex-colors in my GTK theme files the other I used to generate
png files from svg files. (it will do other formats, so we'll need to cut it down to just svg in, png out)

i forgot to comment it in the script, but the export DPI should be 90 to match what you've done with your cursors (if you had forgotten or something) and in the replace color, it's just using the sed command, so first color is the current color, second is the one you want to replace it with.

### CODE REVIEW

**Comment by uloco** [comment]
Tried out the scripts, they are awesome!

**Comment by uloco** [comment]
The next step would be a script to automate the xcursor generation with `xcursorgen`. I really don't have a clue of bash script programming and wanted to learn it first before trying. Do you think you can manage this? I think we would need a list of all cursors, or you could manage this with the script. It is just the simply command `xcursorgen foo.cursor foo` for every file. I will generate a svg file for every layer, so your scripts also work with the animated cursor files.

**Comment by osendott** [comment]
Yeah I can handle the scripting part, that's no problem. When I get home this evening I'll get started. If you want to get the svg's together and the .cursor files. (i'm assuming those have to be done by hand? I saw a couple utilities for automating that part, but they're either outdated or for an ubuntu/debian base, I'm on arch)

**Comment by uloco** [comment]
I pushed single svgs for the animated cursors in the original repository. The `.cursor` files stay the same for the same size (perhaps in the future, we could make it possible to change the size of the cursor too). We just need a script which generates the cursors with `xcursorgen`. This script should just find all `*.cursor` files in the folder `src` and execute the command `xcursorgen somefile.cursor somefile`. Because the cursor is always named the same as the equivalent `.cursor` file, I think we don't need a special list of the cursors. 
What do you think should be done by hand, I didn't understand....

**Comment by osendott** [comment]
the *.cursor files themselves, they are done by hand yes? Also, I pushed a very rough version of the script to my repo here: https://github.com/osendott/numix-cursor/blob/master/automated.sh I'm still @ work, but I had a few mins to tinker, I'll finish it when I get home, but it should be pretty close to doing everything. It'll get a new hex-code from user, use that color to replace another (i'll need to hardcode the color to be replaced tonight) then it'll generate new png files from the .svg files and then pass each one of the .cursor files to xcursorgen. I've tried to comment the code fairly well too, when I get home I'll run back through it and comment better and tweak it (I'm sure there are errors a-plenty), but sometime tonight should have a working script that'll take care of everything. Assuming I understand how this whole process works, which is a big assumption, I've never fooled with any of this prior to a couple days ago.

anyways, once I get it edited I'll test it, and then I'll let you know so you can test it out and if it all works, I'll submit the merge-request

**Comment by uloco** [comment]
yes, the .cursor files are done by hand, because of the changing cursor root point. When we consider to make cursor sizes customizable, this will be more tricky. 
Perhaps there is a way to automate it from here, but I don't know for now.
It's really awesome, that you can handle this bash script madness. I know a few programming languages, but never had time to learn bash. Perhaps some day :P 
Thank you for making this possible!

**Comment by osendott** [comment]
Oh it's no problem at all. I'm not a wiz with bash, but I can do ok. It's a really handy tool. I don't really know how to program, I used to do visual basic back in the day when I used windows, that was about it. Um, I've got 2 versions of the script in my repo, one complete, one I removed all the color-edit stuff, but I'm having troubles. I can run xcursorgen file.cursor output and it works fine, but in the script when I pass the same things to the cli everything appears to work, but the generated files are empty. if you get a chance, could you give it a shot and see if it'll work for you, maybe I've just got some files out of place or something?

**Comment by uloco** [comment]
Great job. I'll have a look tomorrow, it's midnight here in Germany ;)

**Comment by osendott** [comment]
oh haha yeah I guess it is lol

**Pull request merged**
